@startuml ATS Modules
skinparam component {
  BackgroundColor<<simulator>> White
  BackgroundColor<<tool>> Pink
  BackgroundColor<<realTmaSoftware>> AliceBlue
}

skinparam node {
  BackgroundColor<<simulationHardware>> NavajoWhite
  BackgroundColor<<realTmaHardware>> SkyBlue
}

skinparam legend {
  BackgroundColor #GhostWhite
}

legend right
    | Color | Communication type |
    | <#Green> | Modbus |
    | <#Red> | Ethercat |
    | <#Blue> | Custom TCP |
    | <#Orange> | Network Shared Variables (NSV) |
    | <#Purple> | Network Streams |
    | <#DarkTurquoise> | Digital IOs |
    | <#Black> | Unknown (HW Specific) |
    | <#Fuchsia> | TekNSV |
endlegend

node MCC <<realTmaHardware>> {
  component EUI <<realTmaSoftware>>
  component MtMount_OperationManager <<realTmaSoftware>>

  EUI <-l[#Blue]-> MtMount_OperationManager
}

node LinuxMachine <<simulationHardware>> {
  component RobotFramework
  component secondary_axis_sil <<simulator>>
}

node TMA_PXI <<realTmaHardware>>
node AUX_PXI <<realTmaHardware>>
node AXES_PXI <<realTmaHardware>>

node EIB <<realTmaHardware>>
node cRIO <<realTmaHardware>>

node Safety_Controller <<realTmaHardware>>

node speedgoat <<simulationHardware>> {
  component MainAxes_sim <<simulator>>
  component EIB_sim <<simulator>>
  component Drives_sim <<simulator>>

  MainAxes_sim -[#Black]-> EIB_sim
  MainAxes_sim -[#Black]-> Drives_sim
}

node WindowsMachine <<simulationHardware>> {
  interface LocalNSV
  component ReadTMA_PXI_NSV_tool <<tool>>
  component ReadAXES_PXI_NSV_tool <<tool>>
  component ReadLocal_NSV_tool <<tool>>
  component TekNSV_tool <<tool>>
  component BoschPowerSupply_simulator <<simulator>>
  component MotorThermal_simulators <<simulator>>
  component MainPowerSupply_simulator <<simulator>>
  component Limits_simulator <<simulator>>
  component ModbusTemperature_simulators <<simulator>>
  component DeployableExtensions_simulator <<simulator>>
  component OSS_simulator <<simulator>>
  component SpeedgoatManager <<tool>>
  component TopEndChiller_simulator <<simulator>>
  component WriteTekNsvVariables <<tool>>

  LocalNSV <-u[#Blue]-> ReadLocal_NSV_tool
  LocalNSV <-u[#Blue]-> BoschPowerSupply_simulator
  LocalNSV <-u[#Blue]-> MotorThermal_simulators
  LocalNSV <-u[#Blue]-> MainPowerSupply_simulator
  LocalNSV <-u[#Blue]-> Limits_simulator
  LocalNSV <-u[#Blue]-> ModbusTemperature_simulators
  LocalNSV <-u[#Blue]-> DeployableExtensions_simulator
  LocalNSV <-u[#Blue]-> OSS_simulator

  ReadTMA_PXI_NSV_tool <-[#Blue]--> BoschPowerSupply_simulator
  ReadTMA_PXI_NSV_tool <-[#Blue]--> ModbusTemperature_simulators
  ReadTMA_PXI_NSV_tool <-[#Blue]--> MotorThermal_simulators
  ReadTMA_PXI_NSV_tool <-[#Blue]--> MainPowerSupply_simulator
  ReadTMA_PXI_NSV_tool <-[#Blue]--> Limits_simulator

  TekNSV_tool <-[#Blue]--> OSS_simulator
  TekNSV_tool <-[#Blue]--> MotorThermal_simulators
  TekNSV_tool <-[#Blue]--> MainPowerSupply_simulator
  TekNSV_tool <-[#Blue]--> DeployableExtensions_simulator
  TekNSV_tool <-[#Blue]--> Limits_simulator

  ReadAXES_PXI_NSV_tool <-[#Blue]-> MotorThermal_simulators

}

' RobotFramework <--> ReadLocal_NSV_tool
' RobotFramework <--> EUI
' RobotFramework <--> SpeedgoatManager
' RobotFramework <--> secondary_axis_sil
' RobotFramework <--> ReadTMA_PXI_NSV_tool

TMA_PXI <-[#Fuchsia]u-> EUI
TMA_PXI <-[#Fuchsia]-> TekNSV_tool
TMA_PXI <-[#Fuchsia]- WriteTekNsvVariables
AUX_PXI <-[#Fuchsia]u-> EUI
TMA_PXI <-[#Purple]-> AXES_PXI
TMA_PXI <-[#Orange]-> ReadTMA_PXI_NSV_tool

AXES_PXI <-[#Red]-> EIB_sim
AXES_PXI <-[#Red]-> Drives_sim
AXES_PXI <-[#Red]-> cRIO
AXES_PXI <-[#Orange]-> ReadAXES_PXI_NSV_tool

secondary_axis_sil <-[#Green]-> TMA_PXI
Safety_Controller <-[#Green]-> TMA_PXI

AUX_PXI <-[#Green]--> OSS_simulator
AUX_PXI <-[#Green]--> ModbusTemperature_simulators
AUX_PXI <-[#Green]--> TopEndChiller_simulator

SpeedgoatManager <-[#Black]u-> speedgoat

Safety_Controller -[#DarkTurquoise]-> speedgoat
cRIO -[#DarkTurquoise]-> EIB

@enduml